import Head from "next/head";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillYoutube,
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import code from "../public/code.png";
import design from "../public/design.png";
import consulting from "../public/consulting.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import web7 from "../public/img2.png";
import web8 from "../public/img3.png";
import web9 from "../public/img4.png";
import web10 from "../public/img5.png";
import web11 from "../public/img6.png";
import web12 from "../public/img7.png";
import web13 from "../public/img8.png";
import web14 from "../public/img9.png";
import web15 from "../public/img10.png";
import web16 from "../public/img11.png";
import web17 from "../public/img12.png";
import web18 from "../public/img13.png";
import web19 from "../public/img14.png";
import web20 from "../public/img15.png";
import web21 from "../public/img16.png";
import web22 from "../public/img17.png";
import web23 from "../public/img18.png";
import my from '../public/geek.png'
import database from '../public/database.png'
import { FaInstagram, FaLinkedin, FaTwitter, FaTwitterSquare, FaWhatsapp, FaWhatsappSquare } from "react-icons/fa";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">geekdidit</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Afor Success
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Frontend Developer/Data Analyst
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
            Crafting seamless designs, intuitive interfaces, and data-driven solutions. 
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
  {/* LinkedIn */}
  <a href="https://www.linkedin.com/in/success-afor-92bb19222" target="_blank" rel="noopener noreferrer">
    <FaLinkedin />
  </a>

  {/* Twitter */}
  <a href="https://x.com/home" target="_blank" rel="noopener noreferrer">
    <FaTwitter />
  </a>

  {/* Instagram */}
  <a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer">
    <FaInstagram />
  </a>

  {/* WhatsApp */}
  <a href="https://wa.me/+2348154344171" target="_blank" rel="noopener noreferrer">
    <FaWhatsapp />
  </a>
</div>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={my} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
        <div className="text-gray-200">
  <h3 className="text-3xl py-1 text-teal-500">Services I Offer</h3>
  <p className="text-md py-2 leading-8 text-gray-400">
    Over the years, I’ve had the chance to work on exciting projects—helping startups, small businesses, and individuals bring their ideas to life. Whether it’s designing, coding, or making sense of data, I love creating solutions that truly make a difference.
  </p>
  <p className="text-md py-2 leading-8 text-gray-400">
    Here’s what I can help you with:
  </p>
  <ul className="list-disc list-inside text-gray-300">
    <li>
      <span className="text-teal-500 font-bold">Frontend Development:</span> I build clean, responsive, and user-friendly websites that work perfectly on any device.
    </li>
    <li className="mt-2">
      <span className="text-teal-500 font-bold">Design:</span> I turn ideas into beautiful, intuitive designs that connect with users.
    </li>
    <li className="mt-2">
      <span className="text-teal-500 font-bold">Data Analysis:</span> I help you make sense of your data and turn it into insights that drive smarter decisions.
    </li>
  </ul>
  <p className="text-md py-2 leading-8 text-gray-400">
    I’m passionate about blending creativity and technology to create digital experiences that stand out. Let’s build something amazing together!
  </p>
  <p className="text-md py-2 leading-8 text-gray-400">
    I'm a tech enthusiast with a passion for designing intuitive web interfaces and turning raw data into actionable insights.
  </p>
</div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={code} width={100} height={100} />  
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Frontend Development
              </h3>
              <p className="py-2">
              Have a website idea? Let’s build it with clean, responsive code and seamless functionality!
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">HTML</p>
              <p className="text-gray-800 py-1">CSS</p>
              <p className="text-gray-800 py-1">JavaScript</p>
              <p className="text-gray-800 py-1">TailwindCSS</p>
              <p className="text-gray-800 py-1">React, or Vue.js.</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={design} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Design
              </h3>
              <p className="py-2">
              Every great project starts with great design. Let’s create something that’s as beautiful as it is user-friendly!
              </p>
              <h4 className="py-4 text-teal-600">Design Tools I Use</h4>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Canva</p>
              <p className="text-gray-800 py-1">Adobe XD</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={database} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">Data Analysis</h3>
              <p className="py-2">
              Your data tells a story—let me help you uncover insights and make smarter decisions.
              </p>
              <h4 className="py-4 text-teal-600">Tools I Use</h4>
              <p className="text-gray-800 py-1">Excel</p>
              <p className="text-gray-800 py-1">Google Spreadsheet</p>
              <p className="text-gray-800 py-1">Tableau</p>
              <p className="text-gray-800 py-1">PostgreSQL</p>
              <p className="text-gray-800 py-1">Python (Pandas, NumPy).</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 text-teal-500">My Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-400">
            Here’s a collection of projects I’ve worked on, each one a reflection of my passion for creating amazing digital experiences. From building responsive websites to designing intuitive interfaces and making sense of complex data, these projects showcase what I love to do.
            Take a look around.
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I hope you’ll find something that resonates with you!
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web1}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web2}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web3}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web4}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web5}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web6}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web7}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web8}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web9}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web10}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web11}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web12}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web13}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web14}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web15}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web16}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web17}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web18}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web19}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web20}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web21}
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={web22}
              />
            </div>
          </div>
        </section>
        <footer className="bg-gray-900 text-gray-200 py-8">
  <div className="container mx-auto px-4">
    {/* Social Media Icons */}
    <div className="flex justify-center md:justify-start gap-6 mb-6">
      <a href="https://www.linkedin.com/in/success-afor-92bb19222" target="_blank" rel="noopener noreferrer">
        <FaLinkedin className="text-2xl hover:text-teal-400" />
      </a>
      <a href="https://x.com/home" target="_blank" rel="noopener noreferrer">
        <FaTwitter className="text-2xl hover:text-teal-400" />
      </a>
      <a href="https://www.instagram.com/" target="_blank" rel="noopener noreferrer">
        <FaInstagram className="text-2xl hover:text-teal-400" />
      </a>
      <a href="https://wa.me/+2348154344171" target="_blank" rel="noopener noreferrer">
        <FaWhatsapp className="text-2xl hover:text-teal-400" />
      </a>
    </div>

    {/* Divider */}
    <div className="border-t border-gray-700 my-6"></div>

    {/* Bottom Section */}
    <div className="flex flex-col md:flex-row justify-between items-center">
      {/* Copyright */}
      <p className="text-sm text-gray-400 text-center md:text-left">
        © 2024 GeekDidIt. All rights reserved.
      </p>

      {/* Back to Top */}
      <a href="#top" className="text-teal-400 hover:underline mt-4 md:mt-0">
        Back to Top ↑
      </a>
    </div>
  </div>
</footer>

      </main>
    </div>
  );
}
